      language: node_js
      node_js:
      - "0.10"
      before_install:
      - "curl -L https://raw.githubusercontent.com/marcodejongh/travis-ci-meteor-packages/packaging_preview/configure.sh | /bin/sh"
      branches:
        only:
          - master
